services:
  api1: &api
    build: .
    container_name: api1
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - PORT=8000
    command: gunicorn run:app -w 2 -b 0.0.0.0:8000
    expose:
      - "8000"

  api2:
    <<: *api
    container_name: api2
    command: gunicorn run:app -w 2 -b 0.0.0.0:8001
    environment:
      - PORT=8001
    expose:
      - "8001"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api1:
        condition: service_started
      api2:
        condition: service_started